[package]
name = "djengine-analysis"
version = "0.1.0"
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[dependencies]
anyhow.workspace = true
aubio-rs.workspace = true
serde.workspace = true
symphonia.workspace = true
thiserror.workspace = true

[dev-dependencies]
djengine-core = { path = "../djengine-core" }

